# Generated by Django 3.0.5 on 2020-04-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='내용')),
                ('who', models.CharField(max_length=20, verbose_name='글쓴이')),
            ],
        ),
    ]
