# Generated by Django 3.0.5 on 2020-04-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='merge_pdfs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_file', models.FileField(upload_to='origin/merge/')),
                ('completed_file', models.FileField(blank=True, null=True, upload_to='complete/merge/')),
            ],
        ),
        migrations.CreateModel(
            name='split_pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_file', models.FileField(upload_to='origin/split/')),
                ('completed_file', models.FileField(blank=True, null=True, upload_to='complete/split/')),
            ],
        ),
    ]
